// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqimqdg4ITlGpBmrnBkuPdBC6CxxjcXjQ',
    appId: '1:394880012668:android:65a7bccd22e7c48fcb54f9',
    messagingSenderId: '394880012668',
    projectId: 'merge-finess',
    storageBucket: 'merge-finess.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC90oj5Cz8SqI39FvDlKSGpfnqFwW8rygc',
    appId: '1:394880012668:ios:552a701beb22b05ccb54f9',
    messagingSenderId: '394880012668',
    projectId: 'merge-finess',
    storageBucket: 'merge-finess.firebasestorage.app',
    iosClientId: '394880012668-qpnil8s75kcg9srmr9g5qtie1vsdpgn0.apps.googleusercontent.com',
    iosBundleId: 'com.mergefitness.mergeFitness',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA35JhkIkQpF-m-IqBgyTo2w7bkUCGlHuU',
    appId: '1:394880012668:web:0b9e69fdf32aa9e6cb54f9',
    messagingSenderId: '394880012668',
    projectId: 'merge-finess',
    authDomain: 'merge-finess.firebaseapp.com',
    storageBucket: 'merge-finess.firebasestorage.app',
    measurementId: 'G-YMH0FG4M05',
  );

}